### ISSUE TITLE
Bug parsing desember

### ISSUE THREAD

**Issue by N0K0** [N0K0/timelist_generators#7]
```python
neon@nvm ~/uio $ python penger.py -m 12 -y 16
Traceback (most recent call last):
  File "penger.py", line 678, in <module>
    penger = Penger()
  File "penger.py", line 609, in __init__
    self.parse_timesheet()
  File "penger.py", line 271, in parse_timesheet
    date_start, date_end = date_range()
  File "penger.py", line 239, in date_range
    date_end = datetime(self.args.y, self.args.m + 1, 1)
ValueError: month must be in 1..12
```

**Comment by N0K0** [comment]
https://github.com/N0K0/timelist_generators/commit/f243ee133e46ace82b77eace974b487be4802fb0#diff-c5321c4f00bbced7090f52a1fa5f28a9

Fix'd
